language: android
dist: trusty
android:
 components:
    - build-tools-29.0.2
    - android-29
    - extra
script:
  - sonar-scanner
addons: 
 sonarqube:
organization: "nguyenthingoclen"
token:
  secure: "raCAJhaF9S0bSrrFQUVnQmtgdgEtv/vFvOTb9K3SnkfCTXaHrjdcnuJ/dOlbVZauqZw77iRP+jI2sCY1KsM8dBgMUDI46Q4hEjZpgN1pu0FL/O1vjglA5q/aT4ZRl/MpbYXVn2bD1Mf7SoJ2muSOsU1Wuem85KOTWxckhxCKOy50TYlVY9K9kXgVimaz0snq0zDKxwmTfaMvc7E30iSXbPyKo+3z70cWJyFaFZ8wz32t0vnsm62Azo3diSPmV26PFr1E+DNIURL3DL2MG79Gxkxqa6pu8Ltvr1/kAqid/XBMpyCo8Fo2hxssIWSiq8M5XN9EE5WHYzL/NTOvnj62XuDTBLcB9dZL/H8BVTv1mIBXkfT5DqaAriCOMDpBZQgCMGoAguPo9e/a/WFQeuhoHTjQkyzTeHX4DLhs/tg4tKrDhrQOV7y6nNf2t/BWCwnkeqm9G6DI8bZP27vhFn2sNgVTfIXX2lRjizBohQ/ybaZhGbfLQP/VgOf9FZTQcmAPsKFZen0jJJ3M/GaOK1nelqZ8KjWPuKYbG6jJuDCco+Fth8jzi0cT3dKTisWAW73Knm0rJJRrPl57VEZvCUNjermvNQijqw2hsxF5utqiILs7DojZkqkHA6MIUkJJvobWlcbwbbGe05MefhoEymapwLBVD+512FMUOQw83Gwbe+8="
