language: android
dist: trusty
android:
 components:
    - build-tools-29.0.2
    - android-29
    - extra
script:
  - sonar-scanner
addons: 
 sonarqube:
organization: "nguyenthingoclen"
token:
secure: 0db2212a30425d0ef953e9bc2c9a6d424715a88f

