language: android
dist: trusty
android:
 components:
    - build-tools-29.0.2
    - android-29
    - extra
script:
  - sonar-scanner
addons: 
 sonarqube:
organization: "nguyenthingoclen"
token:
secure: cbd02f57691ed34e661b2aab16aa744d67cc8c54

