language: android
dist: trusty
android:
 components:
    - build-tools-29.0.2
    - android-29
    - extra
script:
  - sonar-scanner
addons: 
 sonarqube:
organization: "nguyenthingoclen"
token:
secure:"jWv9dODVh5PJD5uIixQvyKxdRmWcT5ppYZ3yrWQjmhPAnSTTfYJPTrLzUx+58R+/+DWnMgtxut2+ZQOeSQqEJVEsZiXFCTUau8OjLSxF3zx1vebt/VIjmRakNHpOinlR7izFjfWasirM40+QCREGVYYEK7t5MkUz11R3PwAZ7aulOC4ab6jhzgud6l3fWGCBLsN6dS9mB7CPmFOMYHbcgUlgpRyeNwsTezSwrFmjSHblyzet+gMB5H2W0NYZ5HPQLShtdlSdSwikIzF+qeLX/LXjHqESj8zUuqXuR0ai9Kr2HRZAYJ5LFuXUKfb0R4O4N69tokHQtcYHYd3tQpbfraSMdnrCe5jb5j0EP0SJHpLQAaFTDoTqy56dFn918Chryjp328PyrgW+ae8ixOGmTD0nBnsUib6uILkiDwrc4NmZH7ao0ELZaTxsLDf5VSzOgaP5n6Bp0bf+oCxfmk36Mp/ielyGD3lgBQnB7TZ/rtoeqWvZctEhITuvKROs/rAcKmcpQ8Tlx+Zlr5KD1dLI2TF5gdRgcjEugEu8IfIkRtr0Uaag1R8KkRU7W9efxOUkIQjiaksnJXsIlUFRmi6AI5kmMtyKzYdtPcRMPGE2bR8O45i1XChwJOBOxRDBu9b852nKnzWrKrekMkxXAnxs5b+m53zlk9cYUP7D/oXmfAw="

